// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// firebase_auth, cloud_firestore, firebase_storage
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJbWv8sKOukL7THwLeqpGwVgqRfsaBWDg',
    appId: '1:785113473073:android:a03c90a3029d3d558ef510',
    messagingSenderId: '785113473073',
    projectId: 'whatsapp--backend-c5cfb',
    storageBucket: 'whatsapp--backend-c5cfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGPnjoDLqSyyCm7reGkiroVTifz48PXlk',
    appId: '1:785113473073:ios:bf0a0ca46e8aae318ef510',
    messagingSenderId: '785113473073',
    projectId: 'whatsapp--backend-c5cfb',
    storageBucket: 'whatsapp--backend-c5cfb.appspot.com',
    iosClientId: '785113473073-mvupodkjig61ga739u8lque81co03754.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
